#!/usr/bin/env python3
"""Script to add more symptoms to reach 200+ total."""

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SYMPTOMS_FILE = PROJECT_ROOT / "data" / "symptoms" / "symptoms_hu.json"

# Additional symptoms to add
additional_symptoms = [
    # More Engine symptoms (ENG026-ENG040)
    {
        "id": "ENG026",
        "category": "engine",
        "name_hu": "Olaj a hűtőfolyadékban",
        "name_en": "Oil in coolant",
        "description_hu": "Olajos, barna vagy tejszerű anyag látható a hűtőfolyadékban",
        "description_en": "Oily, brown or milky substance visible in coolant",
        "severity": "critical",
        "related_dtc_codes": ["P0115", "P0116", "P0117"],
        "possible_causes": ["Hibás hengerfejtömítés", "Repedt hengerfej", "Olajhűtő szivárgás"],
        "diagnostic_steps": ["Ellenőrizze a hűtőfolyadékot", "Végezzen nyomás tesztet", "Vizsgálja az olajhűtőt"],
        "keywords": ["olaj", "hűtőfolyadék", "tejszerű", "kevert"]
    },
    {
        "id": "ENG027",
        "category": "engine",
        "name_hu": "Hűtőfolyadék az olajban",
        "name_en": "Coolant in oil",
        "description_hu": "Az olaj tejszerű, habos, vagy a szint növekszik",
        "description_en": "Oil appears milky, foamy, or level increases",
        "severity": "critical",
        "related_dtc_codes": ["P0115", "P0116"],
        "possible_causes": ["Hibás hengerfejtömítés", "Repedt motorblokk", "Olajhűtő hiba"],
        "diagnostic_steps": ["Ellenőrizze az olaj pálcát", "Végezzen kipufogógáz tesztet", "Vizsgálja az olajhűtőt"],
        "keywords": ["olaj", "habos", "tejszerű", "hűtőfolyadék"]
    },
    {
        "id": "ENG028",
        "category": "engine",
        "name_hu": "Motor sípolás gyorsításkor",
        "name_en": "Whistling noise on acceleration",
        "description_hu": "Éles fütyülő vagy sípoló hang hallható gyorsításkor",
        "description_en": "Sharp whistling or squealing noise heard during acceleration",
        "severity": "medium",
        "related_dtc_codes": ["P0234", "P0299"],
        "possible_causes": ["Turbó szivárgás", "Töltőlevegő cső repedés", "Vakuumszivárgás"],
        "diagnostic_steps": ["Ellenőrizze a töltőlevegő csöveket", "Vizsgálja a turbót", "Keressen szivárgást"],
        "keywords": ["sípolás", "fütyülés", "turbó", "gyorsítás"]
    },
    {
        "id": "ENG029",
        "category": "engine",
        "name_hu": "Motor nem gyorsul 3000 RPM felett",
        "name_en": "Engine won't rev past 3000 RPM",
        "description_hu": "A motor fordulatszáma nem emelkedik 3000 RPM fölé",
        "description_en": "Engine RPM won't increase above 3000",
        "severity": "high",
        "related_dtc_codes": ["P0100", "P0101", "P0120"],
        "possible_causes": ["Vészüzemmód aktív", "Üzemanyag szűrő eltömődött", "Turbó hiba"],
        "diagnostic_steps": ["Olvassa ki a hibakódokat", "Ellenőrizze az üzemanyag szűrőt", "Vizsgálja a turbót"],
        "keywords": ["nem gyorsul", "vészüzem", "fordulatszám"]
    },
    {
        "id": "ENG030",
        "category": "engine",
        "name_hu": "Start-stop rendszer nem működik",
        "name_en": "Start-stop system not working",
        "description_hu": "Az automatikus start-stop rendszer nem kapcsolja ki a motort",
        "description_en": "Automatic start-stop system doesn't shut off engine",
        "severity": "low",
        "related_dtc_codes": ["P0562", "P0563"],
        "possible_causes": ["Gyenge akkumulátor", "Klíma túl nagy terhelés", "Hűtőfolyadék hőmérséklet"],
        "diagnostic_steps": ["Tesztelje az akkumulátort", "Ellenőrizze a rendszer feltételeket", "Vizsgálja a szenzorokat"],
        "keywords": ["start-stop", "nem kapcsol ki", "akkumulátor"]
    },
    {
        "id": "ENG031",
        "category": "engine",
        "name_hu": "Olajnyomás figyelmeztető lámpa",
        "name_en": "Oil pressure warning light",
        "description_hu": "Az olajnyomás figyelmeztető lámpa világít a műszerfalon",
        "description_en": "Oil pressure warning light illuminated on dashboard",
        "severity": "critical",
        "related_dtc_codes": [],
        "possible_causes": ["Alacsony olajszint", "Hibás olajnyomás szenzor", "Olajpumpa hiba"],
        "diagnostic_steps": ["Álljon meg biztonságosan", "Ellenőrizze az olajszintet", "Tesztelje az olajnyomást"],
        "keywords": ["olajnyomás", "lámpa", "figyelmeztetés"]
    },
    {
        "id": "ENG032",
        "category": "engine",
        "name_hu": "Motor rosszul jár hidegben",
        "name_en": "Engine runs rough when cold",
        "description_hu": "A motor egyenetlenül jár amíg fel nem melegszik",
        "description_en": "Engine runs unevenly until warmed up",
        "severity": "medium",
        "related_dtc_codes": ["P0115", "P0128", "P0171"],
        "possible_causes": ["Hideg indítási dúsítás hiba", "Hibás hűtőfolyadék szenzor", "Gyújtógyertya kopás"],
        "diagnostic_steps": ["Ellenőrizze a hűtőfolyadék szenzort", "Vizsgálja a gyújtógyertyákat", "Olvassa ki a kódokat"],
        "keywords": ["hideg", "egyenetlen", "bemelegedés"]
    },
    {
        "id": "ENG033",
        "category": "engine",
        "name_hu": "Ékszíj csikorgás",
        "name_en": "Serpentine belt squeal",
        "description_hu": "Sivító vagy csikorgó hang az ékszíj területéről",
        "description_en": "Squealing or chirping noise from serpentine belt area",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Kopott ékszíj", "Rossz feszítő", "Hibás csapágy"],
        "diagnostic_steps": ["Vizuálisan ellenőrizze a szíjat", "Vizsgálja a feszítőt", "Hallgassa meg a csapágyakat"],
        "keywords": ["ékszíj", "sivítás", "csikorgás"]
    },
    {
        "id": "ENG034",
        "category": "engine",
        "name_hu": "Vezérlés zörgés hideg indításkor",
        "name_en": "Timing chain rattle on cold start",
        "description_hu": "Zörgő hang a vezérlés területéről hideg indítás után",
        "description_en": "Rattling noise from timing area after cold start",
        "severity": "high",
        "related_dtc_codes": ["P0340", "P0341"],
        "possible_causes": ["Nyúlt vezérlánc", "Kopott láncfeszítő", "Alacsony olajnyomás"],
        "diagnostic_steps": ["Hallgassa meg a motort hidegen", "Ellenőrizze az olajszintet", "Vizsgálja a láncfeszítőt"],
        "keywords": ["vezérlánc", "zörgés", "hideg indítás"]
    },
    {
        "id": "ENG035",
        "category": "engine",
        "name_hu": "Vezérműszíj csúszás",
        "name_en": "Timing belt slipping",
        "description_hu": "Motor rosszul jár, gyújtási időzítés hiba gyanúja",
        "description_en": "Engine runs poorly, suspected ignition timing issue",
        "severity": "critical",
        "related_dtc_codes": ["P0340", "P0341", "P0016"],
        "possible_causes": ["Kopott vezérműszíj", "Rossz szíjfeszítő", "Helytelen beszerelés"],
        "diagnostic_steps": ["Ellenőrizze a vezérlési időzítést", "Vizsgálja a szíjat", "Ellenőrizze a feszítőt"],
        "keywords": ["vezérműszíj", "időzítés", "csúszás"]
    },
    {
        "id": "ENG036",
        "category": "engine",
        "name_hu": "Motor ping hang terhelés alatt",
        "name_en": "Engine pinging under load",
        "description_hu": "Fém csörgő hang a motorból erős gyorsításnál",
        "description_en": "Metallic rattling sound from engine during hard acceleration",
        "severity": "medium",
        "related_dtc_codes": ["P0325", "P0326", "P0327"],
        "possible_causes": ["Rossz üzemanyag", "Detonáció", "Kopogásérzékelő hiba"],
        "diagnostic_steps": ["Próbáljon jobb üzemanyagot", "Ellenőrizze a szenzort", "Vizsgálja a gyújtási időzítést"],
        "keywords": ["ping", "kopogás", "terhelés"]
    },
    {
        "id": "ENG037",
        "category": "engine",
        "name_hu": "Turbó túlfutás",
        "name_en": "Turbo overspeeding",
        "description_hu": "Turbó túl nagy töltőnyomást produkál",
        "description_en": "Turbo producing excessive boost pressure",
        "severity": "high",
        "related_dtc_codes": ["P0234", "P0235"],
        "possible_causes": ["Hibás wastegate", "Boost szolenoid hiba", "ECU probléma"],
        "diagnostic_steps": ["Mérje a töltőnyomást", "Ellenőrizze a wastegate-et", "Vizsgálja a szolenoidot"],
        "keywords": ["turbó", "túlfutás", "boost"]
    },
    {
        "id": "ENG038",
        "category": "engine",
        "name_hu": "PCV rendszer hiba",
        "name_en": "PCV system fault",
        "description_hu": "Kartergáz visszavezetés rendszer hibája",
        "description_en": "Crankcase ventilation system malfunction",
        "severity": "medium",
        "related_dtc_codes": ["P0171", "P0172"],
        "possible_causes": ["Eltömődött PCV szelep", "Szivárgó csövek", "Membránsérülés"],
        "diagnostic_steps": ["Ellenőrizze a PCV szelepet", "Vizsgálja a csöveket", "Tesztelje a vákuumot"],
        "keywords": ["PCV", "kartergáz", "szelep"]
    },
    {
        "id": "ENG039",
        "category": "engine",
        "name_hu": "Vario szelepes rendszer hiba",
        "name_en": "Variable valve timing fault",
        "description_hu": "VVT/VANOS rendszer hibakód vagy működési zavar",
        "description_en": "VVT/VANOS system fault code or malfunction",
        "severity": "medium",
        "related_dtc_codes": ["P0010", "P0011", "P0012", "P0016"],
        "possible_causes": ["Szolenoid hiba", "Olajszennyezés", "Mechanikai kopás"],
        "diagnostic_steps": ["Olvassa ki a kódokat", "Ellenőrizze az olaj állapotát", "Vizsgálja a szolenoidokat"],
        "keywords": ["VVT", "VANOS", "változó szelepvezérlés"]
    },
    {
        "id": "ENG040",
        "category": "engine",
        "name_hu": "Szívósor csappantyú hiba",
        "name_en": "Intake manifold flap fault",
        "description_hu": "Szívócső váltó csappantyúk hibája",
        "description_en": "Intake manifold runner control flaps malfunction",
        "severity": "medium",
        "related_dtc_codes": ["P2004", "P2005", "P2006", "P2007"],
        "possible_causes": ["Beragadt csappantyú", "Motor hiba", "Szénlerakódás"],
        "diagnostic_steps": ["Ellenőrizze a csappantyúkat", "Tisztítsa a szívócsövet", "Vizsgálja a motorokat"],
        "keywords": ["szívócső", "csappantyú", "IMRC"]
    },
    # More Transmission symptoms (TRN011-TRN020)
    {
        "id": "TRN011",
        "category": "transmission",
        "name_hu": "DSG váltó rángatás",
        "name_en": "DSG jerking/shuddering",
        "description_hu": "Dupla kuplungos váltó rángatózik alacsony sebességnél",
        "description_en": "Dual clutch transmission jerks at low speeds",
        "severity": "medium",
        "related_dtc_codes": ["P0730", "P0741"],
        "possible_causes": ["Mechatronika hiba", "Kuplung kopás", "Szoftver probléma"],
        "diagnostic_steps": ["Olvassa ki a hibakódokat", "Végezzen adaptációs resetet", "Vizsgálja a mechatronikát"],
        "keywords": ["DSG", "rángatás", "dupla kuplung"]
    },
    {
        "id": "TRN012",
        "category": "transmission",
        "name_hu": "CVT váltó búgás",
        "name_en": "CVT whining noise",
        "description_hu": "CVT váltó búgó vagy nyöszörgő hangot ad",
        "description_en": "CVT transmission makes whining or humming noise",
        "severity": "medium",
        "related_dtc_codes": ["P0730"],
        "possible_causes": ["Szíj kopás", "Alacsony olajszint", "Szivattyú hiba"],
        "diagnostic_steps": ["Ellenőrizze az olajszintet", "Hallgassa meg a zajt", "Vizsgálja a szíjat"],
        "keywords": ["CVT", "búgás", "fokozatmentes"]
    },
    {
        "id": "TRN013",
        "category": "transmission",
        "name_hu": "Automata váltó forró",
        "name_en": "Automatic transmission overheating",
        "description_hu": "Váltó hőmérséklet figyelmeztető, forró váltó olaj",
        "description_en": "Transmission temperature warning, hot transmission fluid",
        "severity": "high",
        "related_dtc_codes": ["P0700", "P0730"],
        "possible_causes": ["Alacsony olajszint", "Hibás hűtő", "Túlterhelés"],
        "diagnostic_steps": ["Ellenőrizze az olajszintet", "Vizsgálja a hűtőt", "Csökkentse a terhelést"],
        "keywords": ["forró", "túlmelegedés", "váltó"]
    },
    {
        "id": "TRN014",
        "category": "transmission",
        "name_hu": "Tolatásba nem kapcsol",
        "name_en": "Won't engage reverse",
        "description_hu": "A váltó nem kapcsol tolatásba",
        "description_en": "Transmission won't engage reverse gear",
        "severity": "high",
        "related_dtc_codes": ["P0700", "P0730"],
        "possible_causes": ["Szolenoid hiba", "Kuplung probléma", "Mechanikai hiba"],
        "diagnostic_steps": ["Olvassa ki a kódokat", "Ellenőrizze az olajszintet", "Vizsgálja a szolenoidokat"],
        "keywords": ["tolatás", "nem kapcsol", "hátra"]
    },
    {
        "id": "TRN015",
        "category": "transmission",
        "name_hu": "Kézi váltó csikorog",
        "name_en": "Manual transmission grinding",
        "description_hu": "Csiszoló vagy csikorgó hang váltáskor",
        "description_en": "Grinding or crunching noise when shifting",
        "severity": "high",
        "related_dtc_codes": [],
        "possible_causes": ["Kopott szinkrongyűrű", "Kuplung nem old ki", "Váltómű kopás"],
        "diagnostic_steps": ["Ellenőrizze a kuplung működését", "Vizsgálja a váltómű olajat", "Tesztelje a szinkronokat"],
        "keywords": ["csikorgás", "kézi váltó", "szinkron"]
    },
    {
        "id": "TRN016",
        "category": "transmission",
        "name_hu": "Kuplung pedál nehéz",
        "name_en": "Heavy clutch pedal",
        "description_hu": "A kuplungpedál nehezen nyomható",
        "description_en": "Clutch pedal is hard to press",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Hibás kuplung henger", "Kopott bowden", "Mechanikai elakadás"],
        "diagnostic_steps": ["Ellenőrizze a kuplungfolyadékot", "Vizsgálja a hengereket", "Ellenőrizze a mechanikát"],
        "keywords": ["kuplung", "nehéz pedál", "nyomás"]
    },
    {
        "id": "TRN017",
        "category": "transmission",
        "name_hu": "Kuplung csúszik emelkedőn",
        "name_en": "Clutch slipping on hills",
        "description_hu": "A kuplung csúszik emelkedőn vagy nagy terhelés alatt",
        "description_en": "Clutch slips when going uphill or under heavy load",
        "severity": "high",
        "related_dtc_codes": [],
        "possible_causes": ["Kopott kuplungtárcsa", "Gyenge nyomólap", "Olajos felület"],
        "diagnostic_steps": ["Tesztelje a kuplungot terhelés alatt", "Vizsgálja a kopást", "Ellenőrizze olajszivárgást"],
        "keywords": ["kuplung", "csúszás", "emelkedő"]
    },
    {
        "id": "TRN018",
        "category": "transmission",
        "name_hu": "Váltókar nehezen mozog hidegben",
        "name_en": "Stiff shifter when cold",
        "description_hu": "A váltókar nehezen mozog hideg időben",
        "description_en": "Shift lever hard to move in cold weather",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Besűrűsödött váltóolaj", "Merev bowden", "Szinkrongyűrű kopás"],
        "diagnostic_steps": ["Hagyja bemelegedni", "Ellenőrizze az olaj típust", "Vizsgálja a mechanikát"],
        "keywords": ["hideg", "merev", "váltókar"]
    },
    {
        "id": "TRN019",
        "category": "transmission",
        "name_hu": "Sport mód nem működik",
        "name_en": "Sport mode not working",
        "description_hu": "A váltó sport vagy kézi módja nem működik",
        "description_en": "Transmission sport or manual mode not functioning",
        "severity": "low",
        "related_dtc_codes": ["P0700"],
        "possible_causes": ["Kapcsoló hiba", "TCM probléma", "Vezeték hiba"],
        "diagnostic_steps": ["Ellenőrizze a kapcsolót", "Olvassa ki a kódokat", "Vizsgálja a vezetékeket"],
        "keywords": ["sport mód", "kézi mód", "tiptronic"]
    },
    {
        "id": "TRN020",
        "category": "transmission",
        "name_hu": "Automata váltó késik hátramenetből előre",
        "name_en": "Delayed forward from reverse",
        "description_hu": "Késés amikor tolatásból előremenetbe váltunk",
        "description_en": "Delay when shifting from reverse to drive",
        "severity": "medium",
        "related_dtc_codes": ["P0700", "P0730"],
        "possible_causes": ["Szolenoid lassulás", "Alacsony olajszint", "Kuplung kopás"],
        "diagnostic_steps": ["Ellenőrizze az olajszintet", "Vizsgálja a szolenoidokat", "Cserélje az olajat"],
        "keywords": ["késés", "tolatás", "előremenet"]
    },
    # More Electrical symptoms (ELE011-ELE025)
    {
        "id": "ELE011",
        "category": "electrical",
        "name_hu": "Hátsó ablaktörlő nem működik",
        "name_en": "Rear wiper not working",
        "description_hu": "A hátsó ablaktörlő nem működik",
        "description_en": "Rear windshield wiper is not functioning",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Kiégett biztosíték", "Hibás motor", "Kapcsoló hiba"],
        "diagnostic_steps": ["Ellenőrizze a biztosítékot", "Tesztelje a motort", "Vizsgálja a kapcsolót"],
        "keywords": ["ablaktörlő", "hátsó", "nem működik"]
    },
    {
        "id": "ELE012",
        "category": "electrical",
        "name_hu": "Első ablaktörlő lassú",
        "name_en": "Slow front wipers",
        "description_hu": "Az első ablaktörlők lassabban mozognak a normálisnál",
        "description_en": "Front wipers move slower than normal",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Kopott motor", "Rossz földelés", "Mechanikai elakadás"],
        "diagnostic_steps": ["Ellenőrizze a motort", "Vizsgálja a földelést", "Tisztítsa a mechanikát"],
        "keywords": ["ablaktörlő", "lassú", "első"]
    },
    {
        "id": "ELE013",
        "category": "electrical",
        "name_hu": "Immobilizer hiba",
        "name_en": "Immobilizer fault",
        "description_hu": "Az immobilizer rendszer nem engedi a motor indítását",
        "description_en": "Immobilizer system prevents engine start",
        "severity": "high",
        "related_dtc_codes": [],
        "possible_causes": ["Kulcs probléma", "Antenna hiba", "ECU kommunikáció"],
        "diagnostic_steps": ["Próbáljon tartalék kulcsot", "Ellenőrizze az antennát", "Vizsgálja az ECU-t"],
        "keywords": ["immobilizer", "nem indul", "kulcs"]
    },
    {
        "id": "ELE014",
        "category": "electrical",
        "name_hu": "Ködlámpa nem világít",
        "name_en": "Fog lights not working",
        "description_hu": "Az első vagy hátsó ködlámpák nem működnek",
        "description_en": "Front or rear fog lights are not functioning",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Kiégett izzó", "Biztosíték", "Kapcsoló hiba"],
        "diagnostic_steps": ["Ellenőrizze az izzót", "Vizsgálja a biztosítékot", "Tesztelje a kapcsolót"],
        "keywords": ["ködlámpa", "nem világít", "izzó"]
    },
    {
        "id": "ELE015",
        "category": "electrical",
        "name_hu": "Sebességmérő nem működik",
        "name_en": "Speedometer not working",
        "description_hu": "A sebességmérő nem mutat vagy hibásan mutat",
        "description_en": "Speedometer shows no reading or incorrect reading",
        "severity": "medium",
        "related_dtc_codes": ["P0500", "P0720"],
        "possible_causes": ["Sebesség szenzor hiba", "Műszerfal hiba", "Vezeték probléma"],
        "diagnostic_steps": ["Ellenőrizze a szenzort", "Vizsgálja a műszerfalat", "Tesztelje a vezetékeket"],
        "keywords": ["sebességmérő", "nem mutat", "műszerfal"]
    },
    {
        "id": "ELE016",
        "category": "electrical",
        "name_hu": "Irányjelző gyorsan villog",
        "name_en": "Fast turn signal blinking",
        "description_hu": "Az irányjelző a normálisnál gyorsabban villog",
        "description_en": "Turn signal blinks faster than normal",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Kiégett izzó", "Rossz relé", "LED utólagos beszerelés"],
        "diagnostic_steps": ["Ellenőrizze az összes irányjelző izzót", "Vizsgálja a relét", "Cserélje a kiégett izzót"],
        "keywords": ["irányjelző", "gyors villogás", "izzó"]
    },
    {
        "id": "ELE017",
        "category": "electrical",
        "name_hu": "Ülésfűtés nem működik",
        "name_en": "Seat heater not working",
        "description_hu": "Az ülés fűtése nem működik vagy gyorsan kikapcsol",
        "description_en": "Seat heater not working or turns off quickly",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Kiégett fűtőszál", "Kapcsoló hiba", "Biztosíték"],
        "diagnostic_steps": ["Ellenőrizze a biztosítékot", "Tesztelje a kapcsolót", "Vizsgálja a fűtőelemet"],
        "keywords": ["ülésfűtés", "nem melegít", "ülés"]
    },
    {
        "id": "ELE018",
        "category": "electrical",
        "name_hu": "Tolatókamera nem működik",
        "name_en": "Backup camera not working",
        "description_hu": "A tolatókamera képe nem jelenik meg",
        "description_en": "Backup camera image doesn't appear",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Kamera hiba", "Vezeték probléma", "Képernyő hiba"],
        "diagnostic_steps": ["Ellenőrizze a kamerát", "Vizsgálja a csatlakozókat", "Tesztelje a képernyőt"],
        "keywords": ["tolatókamera", "nem működik", "kép"]
    },
    {
        "id": "ELE019",
        "category": "electrical",
        "name_hu": "Parkolószenzor hibás",
        "name_en": "Parking sensor fault",
        "description_hu": "A parkolószenzor folyamatosan sípol vagy nem működik",
        "description_en": "Parking sensor constantly beeping or not working",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Szennyezett szenzor", "Hibás szenzor", "Vezeték probléma"],
        "diagnostic_steps": ["Tisztítsa a szenzorokat", "Ellenőrizze a csatlakozókat", "Cserélje a hibás szenzort"],
        "keywords": ["parkolószenzor", "sípol", "PDC"]
    },
    {
        "id": "ELE020",
        "category": "electrical",
        "name_hu": "Tempomat nem működik",
        "name_en": "Cruise control not working",
        "description_hu": "A tempomat nem kapcsol be vagy nem tartja a sebességet",
        "description_en": "Cruise control won't engage or doesn't maintain speed",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Fékkapcsoló hiba", "Kapcsoló hiba", "ECU probléma"],
        "diagnostic_steps": ["Ellenőrizze a féklámpát", "Vizsgálja a kormánykapcsolót", "Olvassa ki a kódokat"],
        "keywords": ["tempomat", "sebesség tartó", "nem működik"]
    },
    {
        "id": "ELE021",
        "category": "electrical",
        "name_hu": "Kulcs nélküli belépés nem működik",
        "name_en": "Keyless entry not working",
        "description_hu": "A kulcs nélküli belépés nem nyitja az ajtókat",
        "description_en": "Keyless entry system doesn't unlock doors",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Lemerült kulcs elem", "Antenna hiba", "Rendszer hiba"],
        "diagnostic_steps": ["Cserélje a kulcs elemet", "Ellenőrizze az antennát", "Vizsgálja a rendszert"],
        "keywords": ["kulcs nélküli", "keyless", "nem nyílik"]
    },
    {
        "id": "ELE022",
        "category": "electrical",
        "name_hu": "Nappali menetfény hiba",
        "name_en": "Daytime running light fault",
        "description_hu": "A nappali menetfény nem működik vagy hibásan",
        "description_en": "Daytime running lights not working or malfunctioning",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["LED hiba", "Biztosíték", "Vezérlő probléma"],
        "diagnostic_steps": ["Ellenőrizze a LED-eket", "Vizsgálja a biztosítékot", "Tesztelje a vezérlőt"],
        "keywords": ["DRL", "nappali fény", "LED"]
    },
    {
        "id": "ELE023",
        "category": "electrical",
        "name_hu": "Automata fényszóró nem működik",
        "name_en": "Auto headlight not working",
        "description_hu": "Az automatikus fényszóró vezérlés nem működik",
        "description_en": "Automatic headlight control is not functioning",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Fényszenzor hiba", "Kapcsoló hiba", "Vezérlő probléma"],
        "diagnostic_steps": ["Ellenőrizze a fényszenzort", "Vizsgálja a kapcsolót", "Tesztelje a vezérlőt"],
        "keywords": ["automata", "fényszóró", "szenzor"]
    },
    {
        "id": "ELE024",
        "category": "electrical",
        "name_hu": "Esőszenzor nem működik",
        "name_en": "Rain sensor not working",
        "description_hu": "Az automatikus ablaktörlő esőszenzor nem működik",
        "description_en": "Automatic wiper rain sensor is not functioning",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Szennyezett szenzor", "Hibás szenzor", "Szélvédő csere után"],
        "diagnostic_steps": ["Tisztítsa a szenzort", "Ellenőrizze a szenzort", "Vizsgálja a csatlakozást"],
        "keywords": ["esőszenzor", "automata törlő", "nem működik"]
    },
    {
        "id": "ELE025",
        "category": "electrical",
        "name_hu": "Elektromos csomagtartó nem működik",
        "name_en": "Power tailgate not working",
        "description_hu": "Az elektromos csomagtartó nyitás/zárás nem működik",
        "description_en": "Power tailgate open/close is not functioning",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Motor hiba", "Szenzor hiba", "Vezérlő probléma"],
        "diagnostic_steps": ["Ellenőrizze a motort", "Vizsgálja a szenzorokat", "Tesztelje a vezérlőt"],
        "keywords": ["csomagtartó", "elektromos", "nem nyílik"]
    },
    # More Brake symptoms (BRK011-BRK020)
    {
        "id": "BRK011",
        "category": "brakes",
        "name_hu": "ESP figyelmeztető lámpa",
        "name_en": "ESP warning light on",
        "description_hu": "Az ESP/menetstabilizátor figyelmeztető lámpa világít",
        "description_en": "ESP/stability control warning light is illuminated",
        "severity": "medium",
        "related_dtc_codes": ["C0035", "C0040", "C0045", "C0050"],
        "possible_causes": ["Keréksebesség szenzor hiba", "Kormányszög szenzor", "ECU hiba"],
        "diagnostic_steps": ["Olvassa ki a hibakódokat", "Ellenőrizze a szenzorokat", "Vizsgálja a vezetékeket"],
        "keywords": ["ESP", "menetstabilizátor", "lámpa"]
    },
    {
        "id": "BRK012",
        "category": "brakes",
        "name_hu": "Fékbetét kopásjelző",
        "name_en": "Brake pad wear indicator",
        "description_hu": "A fékbetét kopásjelző lámpa világít",
        "description_en": "Brake pad wear indicator light is on",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Kopott fékbetét", "Hibás szenzor", "Vezeték sérülés"],
        "diagnostic_steps": ["Ellenőrizze a fékbetét vastagságot", "Vizsgálja a szenzort", "Cserélje a betéteket"],
        "keywords": ["fékbetét", "kopás", "csere"]
    },
    {
        "id": "BRK013",
        "category": "brakes",
        "name_hu": "Fék kopogás lassan haladva",
        "name_en": "Brake clunk at low speed",
        "description_hu": "Kopogó hang a fékekből lassan haladva",
        "description_en": "Clunking noise from brakes at low speed",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Laza féknyereg", "Kopott csapszeg", "Sérült porvédő"],
        "diagnostic_steps": ["Ellenőrizze a féknyereg rögzítését", "Vizsgálja a csapszeget", "Ellenőrizze a porvédőt"],
        "keywords": ["kopogás", "fék", "lassan"]
    },
    {
        "id": "BRK014",
        "category": "brakes",
        "name_hu": "Fékpedál süllyedés álló motorral",
        "name_en": "Brake pedal sinks with engine off",
        "description_hu": "A fékpedál lassan süllyed álló motorral",
        "description_en": "Brake pedal slowly sinks with engine off",
        "severity": "high",
        "related_dtc_codes": [],
        "possible_causes": ["Főfékhenger belső szivárgás", "Fékcső szivárgás", "Féknyereg szivárgás"],
        "diagnostic_steps": ["Ellenőrizze a fékfolyadék szintet", "Keressen szivárgást", "Vizsgálja a főfékhengert"],
        "keywords": ["pedál süllyed", "főfékhenger", "szivárgás"]
    },
    {
        "id": "BRK015",
        "category": "brakes",
        "name_hu": "Fékezés után kerék meleg",
        "name_en": "Wheel hot after braking",
        "description_hu": "Egy vagy több kerék szokatlanul meleg fékezés után",
        "description_en": "One or more wheels unusually hot after braking",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Beragadt féknyereg", "Sérült fékcső", "Rossz fékpofa"],
        "diagnostic_steps": ["Ellenőrizze az összes kereket", "Vizsgálja a féknyergeket", "Ellenőrizze a fékcsöveket"],
        "keywords": ["meleg kerék", "forró", "fék"]
    },
    {
        "id": "BRK016",
        "category": "brakes",
        "name_hu": "Elektromos kézifék hiba",
        "name_en": "Electronic parking brake fault",
        "description_hu": "Az elektromos kézifék nem működik vagy hiba lámpa világít",
        "description_en": "Electronic parking brake not working or fault light on",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Motor hiba", "Vezérlő egység", "Alacsony akkufeszültség"],
        "diagnostic_steps": ["Olvassa ki a hibakódokat", "Ellenőrizze az akkumulátort", "Vizsgálja a motorokat"],
        "keywords": ["elektromos kézifék", "EPB", "hiba"]
    },
    {
        "id": "BRK017",
        "category": "brakes",
        "name_hu": "ABS aktiválódik sima úton",
        "name_en": "ABS activating on smooth road",
        "description_hu": "Az ABS aktiválódik normál fékezésnél sima úton",
        "description_en": "ABS activates during normal braking on smooth road",
        "severity": "medium",
        "related_dtc_codes": ["C0035", "C0040", "C0045", "C0050"],
        "possible_causes": ["Hibás kerékszenzor", "Szennyezett szenzor", "Szenzor légköz"],
        "diagnostic_steps": ["Ellenőrizze a szenzorokat", "Tisztítsa a szenzorgyűrűket", "Vizsgálja a légközt"],
        "keywords": ["ABS", "aktiválódik", "szenzor"]
    },
    {
        "id": "BRK018",
        "category": "brakes",
        "name_hu": "Fék nem enged el teljesen",
        "name_en": "Brakes not fully releasing",
        "description_hu": "A fékek nem engednek el teljesen, autó nehezen gurul",
        "description_en": "Brakes don't fully release, car rolls hard",
        "severity": "high",
        "related_dtc_codes": [],
        "possible_causes": ["Beragadt féknyereg", "Rossz fékcső", "Hibás főfékhenger"],
        "diagnostic_steps": ["Ellenőrizze a kerekek szabadon forgását", "Vizsgálja a féknyergeket", "Ellenőrizze a főfékhengert"],
        "keywords": ["beragadt", "nem enged", "fék"]
    },
    {
        "id": "BRK019",
        "category": "brakes",
        "name_hu": "Fékezéskor autó megrándul",
        "name_en": "Car jerks when braking",
        "description_hu": "Az autó megrándul vagy rázkódik erős fékezéskor",
        "description_en": "Car jerks or shudders during hard braking",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["ABS működés", "Vetemedett tárcsa", "Kopott fékbetét"],
        "diagnostic_steps": ["Ellenőrizze az ABS-t", "Vizsgálja a tárcsákat", "Ellenőrizze a betéteket"],
        "keywords": ["rándul", "rázkódik", "fékezés"]
    },
    {
        "id": "BRK020",
        "category": "brakes",
        "name_hu": "Fék nyikorg tolatáskor",
        "name_en": "Brake squealing in reverse",
        "description_hu": "A fék nyikorog vagy csikorog tolatáskor",
        "description_en": "Brakes squeal or squeak when reversing",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Normális jelenség", "Szennyezett betét", "Rossz betét típus"],
        "diagnostic_steps": ["Tisztítsa a fékeket", "Ellenőrizze a betét állapotát", "Cserélje szükség esetén"],
        "keywords": ["nyikorg", "tolatás", "csikorog"]
    },
    # More Suspension symptoms (SUS011-SUS020)
    {
        "id": "SUS011",
        "category": "suspension",
        "name_hu": "Légrugó szivárgás",
        "name_en": "Air suspension leak",
        "description_hu": "Az autó egyik oldala alacsonyabban van, kompresszor gyakran indul",
        "description_en": "Car sits lower on one side, compressor runs frequently",
        "severity": "high",
        "related_dtc_codes": [],
        "possible_causes": ["Sérült légrugó", "Szivárgó vezeték", "Hibás szelep"],
        "diagnostic_steps": ["Keressen szivárgást szappanos vízzel", "Ellenőrizze a légrugókat", "Vizsgálja a vezetékeket"],
        "keywords": ["légrugó", "szivárgás", "alacsony"]
    },
    {
        "id": "SUS012",
        "category": "suspension",
        "name_hu": "Lengéscsillapító olajszivárgás",
        "name_en": "Shock absorber oil leak",
        "description_hu": "Olaj látható a lengéscsillapítón",
        "description_en": "Oil visible on shock absorber",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Kopott tömítés", "Sérült csillapító", "Korrózió"],
        "diagnostic_steps": ["Vizuálisan ellenőrizze", "Végezzen ugráltatási tesztet", "Cserélje a csillapítót"],
        "keywords": ["lengéscsillapító", "olaj", "szivárgás"]
    },
    {
        "id": "SUS013",
        "category": "suspension",
        "name_hu": "Autó eleje leül fékezéskor",
        "name_en": "Front end dives when braking",
        "description_hu": "Az autó eleje túlzottan leül fékezéskor",
        "description_en": "Front of car dips excessively when braking",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Gyenge első csillapítók", "Törött rugó", "Hibás stabilizátor"],
        "diagnostic_steps": ["Ellenőrizze az első csillapítókat", "Vizsgálja a rugókat", "Tesztelje a stabilizátort"],
        "keywords": ["leül", "eleje", "fékezés"]
    },
    {
        "id": "SUS014",
        "category": "suspension",
        "name_hu": "Autó hátulja kiugrik kanyarban",
        "name_en": "Rear end swings out in corners",
        "description_hu": "Az autó hátulja kicsúszik kanyarodáskor",
        "description_en": "Rear of car slides out when cornering",
        "severity": "high",
        "related_dtc_codes": [],
        "possible_causes": ["Gyenge hátsó csillapítók", "Rossz kerékbeállítás", "Kopott gumik"],
        "diagnostic_steps": ["Ellenőrizze a hátsó csillapítókat", "Vizsgálja a gumikat", "Végezzen kerékbeállítást"],
        "keywords": ["kicsúszik", "hátul", "kanyar"]
    },
    {
        "id": "SUS015",
        "category": "suspension",
        "name_hu": "Stabilizátor rúd zaj",
        "name_en": "Sway bar link noise",
        "description_hu": "Kattogó vagy kopogó zaj a stabilizátor összekötőből",
        "description_en": "Clicking or clunking noise from sway bar link",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Kopott gömbfej", "Laza rögzítés", "Sérült szilentblokk"],
        "diagnostic_steps": ["Mozgassa meg az összekötőt", "Ellenőrizze a rögzítést", "Cserélje ha kopott"],
        "keywords": ["stabilizátor", "kattog", "összekötő"]
    },
    {
        "id": "SUS016",
        "category": "suspension",
        "name_hu": "Adaptív futómű hiba",
        "name_en": "Adaptive suspension fault",
        "description_hu": "Adaptív futómű figyelmeztető lámpa vagy hibás működés",
        "description_en": "Adaptive suspension warning light or malfunction",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Szenzor hiba", "Csillapító hiba", "Vezérlő probléma"],
        "diagnostic_steps": ["Olvassa ki a kódokat", "Ellenőrizze a szenzorokat", "Vizsgálja a csillapítókat"],
        "keywords": ["adaptív", "futómű", "hiba"]
    },
    {
        "id": "SUS017",
        "category": "suspension",
        "name_hu": "Kerékagy csapágy játék",
        "name_en": "Wheel hub bearing play",
        "description_hu": "Játék érezhető a kerékben oldalra mozgatva",
        "description_en": "Play felt in wheel when moved side to side",
        "severity": "high",
        "related_dtc_codes": [],
        "possible_causes": ["Kopott kerékcsapágy", "Laza kerékanya", "Sérült kerékagy"],
        "diagnostic_steps": ["Ellenőrizze a játékot emelőn", "Vizsgálja a kerékanyákat", "Cserélje a csapágyat"],
        "keywords": ["játék", "csapágy", "kerék"]
    },
    {
        "id": "SUS018",
        "category": "suspension",
        "name_hu": "Rugó törés",
        "name_en": "Broken coil spring",
        "description_hu": "Törött rugó, autó egyik oldala lejjebb van",
        "description_en": "Broken spring, one side of car sits lower",
        "severity": "high",
        "related_dtc_codes": [],
        "possible_causes": ["Korrózió", "Fáradás", "Túlterhelés"],
        "diagnostic_steps": ["Vizuálisan ellenőrizze a rugókat", "Mérje a magasságot", "Cserélje a törött rugót"],
        "keywords": ["rugó törés", "alacsony", "egyik oldal"]
    },
    {
        "id": "SUS019",
        "category": "suspension",
        "name_hu": "Lengőkar szilentblokk kopás",
        "name_en": "Control arm bushing wear",
        "description_hu": "Kopott lengőkar szilentblokk, laza érzés a kormányzásban",
        "description_en": "Worn control arm bushing, loose feeling in steering",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Természetes kopás", "Olajszennyezés", "Túlterhelés"],
        "diagnostic_steps": ["Vizsgálja a szilentblokkot", "Ellenőrizze a repedéseket", "Cserélje ha kopott"],
        "keywords": ["szilentblokk", "lengőkar", "kopás"]
    },
    {
        "id": "SUS020",
        "category": "suspension",
        "name_hu": "Teleszkóp felső csapágy zaj",
        "name_en": "Strut top mount noise",
        "description_hu": "Kattanó hang a teleszkóp felfüggesztési pontjából",
        "description_en": "Clicking noise from strut mounting point",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Kopott csapágy", "Laza rögzítés", "Száraz csukló"],
        "diagnostic_steps": ["Ellenőrizze a felső csapágyat", "Vizsgálja a rögzítést", "Kenjen meg ha szükséges"],
        "keywords": ["teleszkóp", "kattanás", "felső"]
    },
    # More AC/Heating symptoms (AC009-AC015)
    {
        "id": "AC009",
        "category": "ac_heating",
        "name_hu": "Klíma kompresszor nem kapcsol be",
        "name_en": "AC compressor not engaging",
        "description_hu": "A klíma kompresszor nem kapcsol be, nincs hűtés",
        "description_en": "AC compressor doesn't engage, no cooling",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Alacsony hűtőközeg", "Hibás kuplung", "Nyomáskapcsoló hiba"],
        "diagnostic_steps": ["Ellenőrizze a hűtőközeg szintet", "Vizsgálja a kuplungot", "Tesztelje a nyomáskapcsolót"],
        "keywords": ["kompresszor", "nem kapcsol", "klíma"]
    },
    {
        "id": "AC010",
        "category": "ac_heating",
        "name_hu": "Klíma hűt majd meleg",
        "name_en": "AC cools then blows warm",
        "description_hu": "A klíma eleinte hűt, majd melegre vált",
        "description_en": "AC cools initially then switches to warm",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Fagyás az elpárologtatón", "Nyomásprobléma", "Hibás szenzor"],
        "diagnostic_steps": ["Ellenőrizze a nyomásokat", "Vizsgálja az elpárologtatót", "Tesztelje a szenzorokat"],
        "keywords": ["váltakozó", "hűt", "meleg"]
    },
    {
        "id": "AC011",
        "category": "ac_heating",
        "name_hu": "Szélvédő fűtés nem működik",
        "name_en": "Heated windshield not working",
        "description_hu": "A fűthető szélvédő nem melegít",
        "description_en": "Heated windshield is not heating",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Megszakadt fűtőszál", "Biztosíték", "Kapcsoló hiba"],
        "diagnostic_steps": ["Ellenőrizze a biztosítékot", "Vizsgálja a fűtőszálakat", "Tesztelje a kapcsolót"],
        "keywords": ["szélvédő fűtés", "nem melegít", "fűtőszál"]
    },
    {
        "id": "AC012",
        "category": "ac_heating",
        "name_hu": "Automata klíma hibás",
        "name_en": "Automatic climate control fault",
        "description_hu": "Az automata klímavezérlés nem működik megfelelően",
        "description_en": "Automatic climate control not functioning properly",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Szenzor hiba", "Vezérlő egység", "Szervomotor hiba"],
        "diagnostic_steps": ["Olvassa ki a kódokat", "Ellenőrizze a szenzorokat", "Vizsgálja a motorokat"],
        "keywords": ["automata klíma", "vezérlés", "nem működik"]
    },
    {
        "id": "AC013",
        "category": "ac_heating",
        "name_hu": "Hátsó légkondicionálás nem működik",
        "name_en": "Rear AC not working",
        "description_hu": "A hátsó légkondicionálás nem fúj vagy nem hűt",
        "description_en": "Rear air conditioning not blowing or not cooling",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Ventilátor hiba", "Szelep hiba", "Eltömődött vezeték"],
        "diagnostic_steps": ["Ellenőrizze a ventilátort", "Vizsgálja a szelepeket", "Ellenőrizze a vezetékeket"],
        "keywords": ["hátsó klíma", "nem működik", "hátsó"]
    },
    {
        "id": "AC014",
        "category": "ac_heating",
        "name_hu": "Recirkuláció nem működik",
        "name_en": "Recirculation not working",
        "description_hu": "A levegő recirkuláció csappantyú nem működik",
        "description_en": "Air recirculation flap is not working",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Motor hiba", "Csappantyú elakadás", "Vezérlő probléma"],
        "diagnostic_steps": ["Hallgassa a motort", "Ellenőrizze a csappantyút", "Vizsgálja a vezérlőt"],
        "keywords": ["recirkuláció", "csappantyú", "nem működik"]
    },
    {
        "id": "AC015",
        "category": "ac_heating",
        "name_hu": "Klíma kompresszor zajos",
        "name_en": "Noisy AC compressor",
        "description_hu": "A klíma kompresszor zajos működés közben",
        "description_en": "AC compressor makes noise during operation",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Kopott csapágy", "Kuplung hiba", "Belső sérülés"],
        "diagnostic_steps": ["Azonosítsa a zaj forrását", "Ellenőrizze a kuplungot", "Vizsgálja a kompresszort"],
        "keywords": ["kompresszor", "zajos", "klíma"]
    },
    # More Fuel system symptoms (FUE007-FUE015)
    {
        "id": "FUE007",
        "category": "fuel_system",
        "name_hu": "Üzemanyag szivattyú zaj",
        "name_en": "Fuel pump noise",
        "description_hu": "Zümmögő vagy búgó hang az üzemanyagtank területéről",
        "description_en": "Humming or whining noise from fuel tank area",
        "severity": "medium",
        "related_dtc_codes": ["P0230", "P0231"],
        "possible_causes": ["Kopott szivattyú", "Alacsony üzemanyagszint", "Sérült vezeték"],
        "diagnostic_steps": ["Hallgassa meg a zajt", "Ellenőrizze az üzemanyagszintet", "Vizsgálja a szivattyút"],
        "keywords": ["szivattyú", "zaj", "zümmög"]
    },
    {
        "id": "FUE008",
        "category": "fuel_system",
        "name_hu": "Motor megakad alacsony üzemanyagszintnél",
        "name_en": "Engine stumbles at low fuel",
        "description_hu": "A motor megakad vagy kihagy alacsony üzemanyagszintnél",
        "description_en": "Engine stumbles or misses at low fuel level",
        "severity": "medium",
        "related_dtc_codes": ["P0190", "P0191"],
        "possible_causes": ["Szennyezett tank", "Hibás szintjelző", "Szivattyú probléma"],
        "diagnostic_steps": ["Tankoljon", "Ellenőrizze a szintjelzőt", "Vizsgálja a tankot"],
        "keywords": ["alacsony", "üzemanyag", "akadozik"]
    },
    {
        "id": "FUE009",
        "category": "fuel_system",
        "name_hu": "Benzingőz szag indítás után",
        "name_en": "Fuel vapor smell after start",
        "description_hu": "Erős benzinszag indítás után, majd elmúlik",
        "description_en": "Strong fuel smell after starting, then fades",
        "severity": "medium",
        "related_dtc_codes": ["P0440", "P0442"],
        "possible_causes": ["EVAP rendszer hiba", "Befecskendező szivárgás", "Normál hideg indítás"],
        "diagnostic_steps": ["Ellenőrizze az EVAP rendszert", "Vizsgálja a befecskendezőket", "Keressen szivárgást"],
        "keywords": ["benzinszag", "indítás", "gőz"]
    },
    {
        "id": "FUE010",
        "category": "fuel_system",
        "name_hu": "Dízel motor füstöl hidegen",
        "name_en": "Diesel smoking when cold",
        "description_hu": "A dízelmotor fehér füstöt ereszt hideg indítás után",
        "description_en": "Diesel engine emits white smoke after cold start",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Normál kondenzáció", "Izzítógyertya hiba", "Befecskendező probléma"],
        "diagnostic_steps": ["Ellenőrizze az izzítógyertyákat", "Vizsgálja a befecskendezőket", "Várja meg a bemelegedést"],
        "keywords": ["dízel", "füst", "hideg"]
    },
    {
        "id": "FUE011",
        "category": "fuel_system",
        "name_hu": "AdBlue rendszer hiba",
        "name_en": "AdBlue system fault",
        "description_hu": "AdBlue figyelmeztető lámpa vagy hibaüzenet",
        "description_en": "AdBlue warning light or fault message",
        "severity": "medium",
        "related_dtc_codes": ["P2201", "P2202"],
        "possible_causes": ["Alacsony AdBlue szint", "Hibás szenzor", "Befagyott AdBlue"],
        "diagnostic_steps": ["Ellenőrizze az AdBlue szintet", "Vizsgálja a szenzort", "Melegítse fel a rendszert"],
        "keywords": ["AdBlue", "SCR", "NOx"]
    },
    {
        "id": "FUE012",
        "category": "fuel_system",
        "name_hu": "Common rail nyomás hiba",
        "name_en": "Common rail pressure fault",
        "description_hu": "Dízelmotornál nyomásvesztés vagy hibakód",
        "description_en": "Diesel engine pressure loss or fault code",
        "severity": "high",
        "related_dtc_codes": ["P0087", "P0088", "P0190", "P0191"],
        "possible_causes": ["Szivárgó befecskendező", "Hibás nyomásszabályzó", "Kopott nagynyomású szivattyú"],
        "diagnostic_steps": ["Olvassa ki a nyomás értékeket", "Ellenőrizze a befecskendezőket", "Vizsgálja a szivattyút"],
        "keywords": ["common rail", "nyomás", "dízel"]
    },
    {
        "id": "FUE013",
        "category": "fuel_system",
        "name_hu": "Üzemanyag víz szenzor",
        "name_en": "Water in fuel warning",
        "description_hu": "Víz az üzemanyagban figyelmeztető lámpa világít",
        "description_en": "Water in fuel warning light is on",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Víz a tankban", "Hibás szenzor", "Szennyezett üzemanyag"],
        "diagnostic_steps": ["Ürítse le a vízleválasztót", "Ellenőrizze a szenzort", "Cserélje az üzemanyagot"],
        "keywords": ["víz", "üzemanyag", "szenzor"]
    },
    {
        "id": "FUE014",
        "category": "fuel_system",
        "name_hu": "Tanksapka hiány figyelmeztető",
        "name_en": "Loose gas cap warning",
        "description_hu": "Figyelmeztető üzenet a tanksapka hiányáról vagy lazaságáról",
        "description_en": "Warning message about missing or loose gas cap",
        "severity": "low",
        "related_dtc_codes": ["P0455", "P0457"],
        "possible_causes": ["Laza tanksapka", "Sérült tömítés", "Hibás szenzor"],
        "diagnostic_steps": ["Ellenőrizze a tanksapkát", "Vizsgálja a tömítést", "Cserélje ha szükséges"],
        "keywords": ["tanksapka", "laza", "figyelmeztetés"]
    },
    {
        "id": "FUE015",
        "category": "fuel_system",
        "name_hu": "Üzemanyag szűrő eltömődött",
        "name_en": "Clogged fuel filter",
        "description_hu": "Motor erővesztés, nehéz gyorsítás, akadozás",
        "description_en": "Engine power loss, difficult acceleration, hesitation",
        "severity": "medium",
        "related_dtc_codes": ["P0087", "P0171"],
        "possible_causes": ["Eltömődött szűrő", "Szennyezett üzemanyag", "Régi szűrő"],
        "diagnostic_steps": ["Ellenőrizze a szűrő korát", "Mérje az üzemanyag nyomást", "Cserélje a szűrőt"],
        "keywords": ["üzemanyag szűrő", "eltömődött", "csere"]
    },
    # More Exhaust symptoms (EXH006-EXH010)
    {
        "id": "EXH006",
        "category": "exhaust",
        "name_hu": "Kipufogó rezgés",
        "name_en": "Exhaust vibration",
        "description_hu": "Rezgés vagy zaj a kipufogó rendszerből",
        "description_en": "Vibration or noise from exhaust system",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Laza rögzítés", "Sérült gumitartó", "Érintkező elemek"],
        "diagnostic_steps": ["Ellenőrizze a rögzítéseket", "Vizsgálja a gumitartókat", "Keressen érintkezést"],
        "keywords": ["kipufogó", "rezgés", "zaj"]
    },
    {
        "id": "EXH007",
        "category": "exhaust",
        "name_hu": "Lambda szenzor hiba",
        "name_en": "Lambda sensor fault",
        "description_hu": "Oxigén szenzor hibakód, magas fogyasztás",
        "description_en": "Oxygen sensor fault code, high fuel consumption",
        "severity": "medium",
        "related_dtc_codes": ["P0130", "P0131", "P0133", "P0135", "P0141"],
        "possible_causes": ["Kopott szenzor", "Vezeték sérülés", "Szennyezett szenzor"],
        "diagnostic_steps": ["Olvassa ki a kódokat", "Ellenőrizze a szenzort", "Cserélje ha szükséges"],
        "keywords": ["lambda", "oxigén", "szenzor"]
    },
    {
        "id": "EXH008",
        "category": "exhaust",
        "name_hu": "Kipufogó korróziós sérülés",
        "name_en": "Exhaust corrosion damage",
        "description_hu": "Rozsdás, lyukas kipufogócső vagy hangtompító",
        "description_en": "Rusty, holey exhaust pipe or muffler",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Korrózió", "Só sérülés", "Öregedés"],
        "diagnostic_steps": ["Vizuálisan ellenőrizze", "Keressen lyukakat", "Cserélje a sérült részeket"],
        "keywords": ["rozsda", "lyukas", "kipufogó"]
    },
    {
        "id": "EXH009",
        "category": "exhaust",
        "name_hu": "NOx szenzor hiba",
        "name_en": "NOx sensor fault",
        "description_hu": "NOx szenzor hibakód dízel járműnél",
        "description_en": "NOx sensor fault code on diesel vehicle",
        "severity": "medium",
        "related_dtc_codes": ["P2201", "P2202", "P2203"],
        "possible_causes": ["Hibás szenzor", "SCR rendszer probléma", "AdBlue hiba"],
        "diagnostic_steps": ["Olvassa ki a kódokat", "Ellenőrizze az AdBlue szintet", "Vizsgálja a szenzort"],
        "keywords": ["NOx", "szenzor", "dízel"]
    },
    {
        "id": "EXH010",
        "category": "exhaust",
        "name_hu": "Kipufogó kondenzáció",
        "name_en": "Exhaust condensation",
        "description_hu": "Víz csepeg a kipufogóból hideg indítás után",
        "description_en": "Water dripping from exhaust after cold start",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Normál kondenzáció", "Hideg időjárás", "Rövid utak"],
        "diagnostic_steps": ["Figyelje meg a mennyiséget", "Ellenőrizze a színt", "Normális ha tiszta víz"],
        "keywords": ["kondenzáció", "víz", "csepeg"]
    },
    # More Cooling symptoms (COO006-COO010)
    {
        "id": "COO006",
        "category": "cooling",
        "name_hu": "Hűtő eltömődött",
        "name_en": "Radiator clogged",
        "description_hu": "A hűtő belülről vagy kívülről eltömődött",
        "description_en": "Radiator clogged internally or externally",
        "severity": "high",
        "related_dtc_codes": ["P0217"],
        "possible_causes": ["Belső lerakódás", "Rovarok és szennyeződés", "Régi hűtőfolyadék"],
        "diagnostic_steps": ["Vizsgálja a hűtőt kívülről", "Ellenőrizze az átfolyást", "Tisztítsa vagy cserélje"],
        "keywords": ["hűtő", "eltömődött", "tisztítás"]
    },
    {
        "id": "COO007",
        "category": "cooling",
        "name_hu": "Kiegyenlítő tartály repedés",
        "name_en": "Expansion tank crack",
        "description_hu": "Repedt kiegyenlítő tartály, folyadékvesztés",
        "description_en": "Cracked expansion tank, fluid loss",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Hőfeszültség", "Öregedés", "Túlnyomás"],
        "diagnostic_steps": ["Ellenőrizze vizuálisan", "Keressen repedéseket", "Cserélje a tartályt"],
        "keywords": ["kiegyenlítő", "tartály", "repedés"]
    },
    {
        "id": "COO008",
        "category": "cooling",
        "name_hu": "Hűtőfolyadék színe rossz",
        "name_en": "Coolant discoloration",
        "description_hu": "A hűtőfolyadék elszíneződött, rozsdás vagy olajos",
        "description_en": "Coolant is discolored, rusty or oily",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Korrózió", "Olajkeveredés", "Régi folyadék"],
        "diagnostic_steps": ["Ellenőrizze a folyadék színét", "Keressen olajszennyezést", "Cserélje a folyadékot"],
        "keywords": ["szín", "hűtőfolyadék", "rozsdás"]
    },
    {
        "id": "COO009",
        "category": "cooling",
        "name_hu": "Fűtőradiátor szivárgás",
        "name_en": "Heater core leak",
        "description_hu": "Hűtőfolyadék szag a belsőben, párás ablak",
        "description_en": "Coolant smell inside, foggy windows",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Korrodált fűtőradiátor", "Sérült csatlakozás", "Repedés"],
        "diagnostic_steps": ["Ellenőrizze a folyadékszintet", "Keressen nedvességet a padlón", "Vizsgálja a fűtőradiátort"],
        "keywords": ["fűtőradiátor", "szivárgás", "szag"]
    },
    {
        "id": "COO010",
        "category": "cooling",
        "name_hu": "Hűtőrendszer túlnyomás",
        "name_en": "Cooling system overpressure",
        "description_hu": "A hűtőcsövek feszesek, sapka gyakran kiold",
        "description_en": "Coolant hoses tense, cap frequently releases",
        "severity": "high",
        "related_dtc_codes": [],
        "possible_causes": ["Hibás sapka", "Hengerfejtömítés szivárgás", "Eltömődött hűtő"],
        "diagnostic_steps": ["Ellenőrizze a sapkát", "Végezzen nyomás tesztet", "Vizsgálja a hengerfejtömítést"],
        "keywords": ["túlnyomás", "sapka", "feszültség"]
    },
    # More Steering symptoms (STR006-STR010)
    {
        "id": "STR006",
        "category": "steering",
        "name_hu": "Kormány vibrál alacsony sebességnél",
        "name_en": "Steering vibration at low speed",
        "description_hu": "A kormány vibrál lassan haladva vagy manőverezve",
        "description_en": "Steering wheel vibrates at low speed or when maneuvering",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Lapos pont a gumin", "Hibás kormánymű", "Kardáncsukló kopás"],
        "diagnostic_steps": ["Ellenőrizze a gumikat", "Vizsgálja a kormányművet", "Ellenőrizze a csuklókat"],
        "keywords": ["vibráció", "lassan", "kormány"]
    },
    {
        "id": "STR007",
        "category": "steering",
        "name_hu": "Szervó pumpa szivárgás",
        "name_en": "Power steering pump leak",
        "description_hu": "Piros vagy barna folyadék szivárog a szervó szivattyúból",
        "description_en": "Red or brown fluid leaking from power steering pump",
        "severity": "medium",
        "related_dtc_codes": [],
        "possible_causes": ["Kopott tömítés", "Sérült cső", "Túlnyomás"],
        "diagnostic_steps": ["Azonosítsa a szivárgás helyét", "Ellenőrizze a csöveket", "Cserélje a tömítéseket"],
        "keywords": ["szervó", "szivárgás", "szivattyú"]
    },
    {
        "id": "STR008",
        "category": "steering",
        "name_hu": "Elektromos kormányrásegítő hiba",
        "name_en": "Electric power steering fault",
        "description_hu": "EPS figyelmeztető lámpa, nehéz vagy hirtelen kormányzás",
        "description_en": "EPS warning light, heavy or jerky steering",
        "severity": "high",
        "related_dtc_codes": [],
        "possible_causes": ["Motor hiba", "Szenzor hiba", "ECU probléma"],
        "diagnostic_steps": ["Olvassa ki a kódokat", "Ellenőrizze a szenzorokat", "Vizsgálja a motort"],
        "keywords": ["EPS", "elektromos", "kormány hiba"]
    },
    {
        "id": "STR009",
        "category": "steering",
        "name_hu": "Kormányoszlop zaj",
        "name_en": "Steering column noise",
        "description_hu": "Kattogó vagy kopogó hang a kormányoszlopból",
        "description_en": "Clicking or knocking noise from steering column",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Laza burkolat", "Kopott csukló", "Száraz mechanika"],
        "diagnostic_steps": ["Ellenőrizze a burkolatot", "Vizsgálja a csuklókat", "Kenjen meg ha szükséges"],
        "keywords": ["kormányoszlop", "kattogás", "zaj"]
    },
    {
        "id": "STR010",
        "category": "steering",
        "name_hu": "Kormány központ nem pontos",
        "name_en": "Steering wheel off-center",
        "description_hu": "A kormány nem egyenes egyenes vezetéskor",
        "description_en": "Steering wheel is not straight when driving straight",
        "severity": "low",
        "related_dtc_codes": [],
        "possible_causes": ["Rossz kerékbeállítás", "Kormánymű állítás", "Gumicsere után"],
        "diagnostic_steps": ["Végezzen kerékbeállítást", "Ellenőrizze a kormánymű beállítást", "Állítsa be a kormányt"],
        "keywords": ["központ", "nem egyenes", "beállítás"]
    }
]

def main():
    # Load existing data
    with open(SYMPTOMS_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    print(f"Current symptoms: {len(data['symptoms'])}")

    # Add new symptoms
    existing_ids = {s['id'] for s in data['symptoms']}
    added = 0
    for symptom in additional_symptoms:
        if symptom['id'] not in existing_ids:
            data['symptoms'].append(symptom)
            existing_ids.add(symptom['id'])
            added += 1

    # Update metadata
    data['metadata']['total_symptoms'] = len(data['symptoms'])
    data['metadata']['generated_at'] = "2026-02-05T00:00:00Z"

    # Save updated data
    with open(SYMPTOMS_FILE, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Added {added} new symptoms")
    print(f"Total symptoms after update: {len(data['symptoms'])}")

    # Print category breakdown
    category_counts = {}
    for s in data['symptoms']:
        cat = s.get('category', 'unknown')
        category_counts[cat] = category_counts.get(cat, 0) + 1

    print("\nSymptoms by category:")
    for cat, count in sorted(category_counts.items()):
        print(f"  {cat}: {count}")

if __name__ == "__main__":
    main()
